### ISSUE TITLE
Response Code 400 - Unifi Software Install 8.6.9

### ISSUE THREAD

**Issue by Nimda11** [MichaelMcCool/Unifi#14]
It worked earlier in the week. I updated the docker image running my Unifi Controller and now I cannot login using this module.

Tried on my local machine and a fresh Sandbox, same issues. Powershell v7.4

```
PS C:\Users\Sam> Connect-UnifiController -ControllerURL $Controller -credentials $Credentials -Verbose
VERBOSE: Domain is __hostname__.
VERBOSE: Requested HTTP/1.1 POST with 80-byte payload
VERBOSE: Received HTTP/1.1 57-byte response of content type application/json
API Connection Error: Response status code does not indicate success: 400 ().
```

triple checked hostname, credentials etc.

**Comment by SuperStark** [comment]
Same error here, clearly a change on Ubiquiti's end. 

@Nimda11 remove your host from the message for privacy.

**Comment by Nimda11** [comment]
> Same error here, clearly a change on Ubiquiti's end.
> 
> @Nimda11 remove your host from the message for privacy.

Yikes! Thanks for the catch.

**Comment by MichaelMcCool** [comment]
Did this affect 8.6.8? The main controller I use is on 8.5.3 still. The controller should be updated tomorrow and see what changes need to be made to let the logins work.

**Comment by MichaelMcCool** [comment]
@SuperStark, @Nimda11 - Please make sure that you are on version 1.0.6 of the Unifi module. This issue has already been fixed. (It is present in 1.0.4.)
