### ISSUE TITLE
Any error from Connect-UnifiController causes the powershell session to exit

### ISSUE THREAD

**Issue by TheGhost2804** [MichaelMcCool/Unifi#2]
Everytime I try Connect-UnifiController and it fails for some reason it closes the powershell window. I could only see the error through the Windows Terminal that I setup not to close on exit.

Connect-UnifiController -ControllerURL $Controller -credentials $Credentials
API Connection Error: The remote server returned an error: (400) Bad Request.

[process exited with code 1]

I think I do know the reason for the 400 error, but that is not the problem that I'm refering to...

**Comment by MichaelMcCool** [comment]
I found the reason for the exit code of 1.  It was a hold-over from when this was a stand-alone script when I was first creating it. I'll get that removed so it no longer exits.

As to the error 400, are you by chance trying to connect to a UDMPro?

**Comment by MichaelMcCool** [comment]
Fixed in 1.0.2
