### ISSUE TITLE
new site setting found: super_fwupdate

### ISSUE THREAD

**Issue by CasperStekelenburg** [MichaelMcCool/Unifi#3]
Found a new site setting with Test-UnifiSiteKnownSetting: **super_fwupdate**.

**Comment by MichaelMcCool** [comment]
Thanks.  Any idea what information is contained in this setting? Do you mind sharing a sanitized output?

**Comment by CasperStekelenburg** [comment]
$UnifiSiteSettings = Get-UnifiSiteSetting
$UnifiSiteSettings.super_fwupdate

available_controller_channels : { release }
available_firmware_channels   : { release }
key                           : super_fwupdate
sso_enabled                   : True
x_sso_token                   : 8058b67c-5d5d-43b3-b311-8e64ef7ced6d
_id                           : c29tZSByYW5kb20gc3RyaW5n

the token and id where changed by me, but this is what I got.

**Comment by MichaelMcCool** [comment]
Thanks! By the look of it, this appears to be a way of changing what release channels the controller and device are subscribed to for delivering firmware updates. This is probably a setting introduced in the new 6.x controller firmware.

The new setting has been added to the code base and will be available in the module in version 1.0.3.
