### ISSUE TITLE
Test-UnifiSiteKnownSetting

### ISSUE THREAD

**Issue by wimternet** [MichaelMcCool/Unifi#7]
Building list of Unifi site settings...
	Processing Default...
	Processing KSOM vzw Campus Rozenberg...
Found new site setting: global_ap. Please inform module maintainer.
Found new site setting: global_switch. Please inform module maintainer.
Found new site setting: teleport. Please inform module maintainer.

**Comment by MichaelMcCool** [comment]
Thank you for the notification about the new site settings. Support has been added in 1.0.4.
