### ISSUE TITLE
what am i doing wrong

### ISSUE THREAD

**Issue by bretthatt** [MichaelMcCool/Unifi#8]
The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch,
     | RemoteCertificateChainErrors

what am i doing wrong?

**Comment by SynitiSmug** [comment]
I have the same issue (I'm using powershell for Mac).  The README has a bit of code that is supposed to ignore self-signed certs but.... no dice :(

**Comment by ghost** [comment]
I'm also having this issue when trying the example code

**Comment by ghost** [comment]
the only workaround I have found for this is to generate the properly signed certificate and import it into unifi. I used our onprem domain CA to do this. 

you can import the certificate once created (on Windows) this way: https://www.orbitsit.co.uk/2022/06/ubiquiti-unifi-controller-ssl-certificate-install-renew-on-windows/

I still cant get it to work however, it may be the case that the API endpoints have changed in the latest release (7.3).

**Comment by MichaelMcCool** [comment]
I've tested this against 8.1.127.0, and have no issues with it. Here is the script I've been using to make the connection to the controller.
```powershell
[String]$Hostname = '<controller IP/Hostname>'
[String]$Port = '8443' # Change this to match the listening port
[String]$UnifiUsername = '<username>'
[String]$UnifiPassword = '<password>'

[String]$Controller = "https://$($hostname):$($port)"

# Enables TLS1.2 -- this is a universal method that works for any dot net version
[Net.ServicePointManager]::SecurityProtocol = [Enum]::ToObject([Net.SecurityProtocolType], 3072)

# Ignore self-signed certificates 
[System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }

# Create a secure credential object
[securestring]$SecPassword=ConvertTo-SecureString $UnifiPassword -AsPlainText -Force
[pscredential]$Credentials=New-Object System.Management.Automation.PSCredential ($UnifiUsername, $SecPassword)

import-module Unifi

# If connecting to a UDMPro, add '-UDMPro' to the following line.
Connect-UnifiController -ControllerURL $Controller -credentials $Credentials
```
