### ISSUE TITLE
Feature Request - Audit Reports and Credential Update

### ISSUE THREAD

**Issue by justnwaters** [MichaelMcCool/Unifi#9]
There are a few things I'm looking to get from the API here:
  - Ability to pull logs from each site. (We have > 20 sites)
  - Check all devices to see if they were upgraded successfully
  - Mass change the SSH Key or Username/Password for all devices within a site
  - Pull insight data (Nearby AP list SSID and signal strength)
  - Pull client list (connection type, port/wap connection, strength/quality)

**Comment by MichaelMcCool** [comment]
Get-UnifiSiteClient will give you the client list.
Get-UnifiSiteKnownAccessPoint will display any nearyby APs (this can be a LOT of data).
For checking that devices were upgraded successfully, you can simply requery the site device list once you have given enough time for the device to update and reboot. Using the -detailed switch will include the firmware version information. (Get-UnifiSiteDevice -name default -detailed)

For logs and changing the site credentials, I will have to investigate and see what is required. I'll add this to my todo list.
